name: CI

on:
  pull_request:
    branches: [ "master", "develop" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "develop" ]
    paths-ignore: [ "docs/**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test
